### ISSUE TITLE
Outdated node-sass gives errors on ubuntu 22.04

### ISSUE THREAD

**Issue by yannickkuypers** [OnroerendErfgoed/thesaurus-widget#104]
Outdated node-sass geeft problemen op ubuntu 22.04. Die is deprecated dus node-sass moet sass worden.

**Comment by cedrikv** [comment]
voor welk project is deze? also: misschien goe moment om naar oerelia te porten?

**Comment by yannickkuypers** [comment]
Deze is voor inventaris ook. Kdenk dat daar inderdaad al een ticket voor bestaat om die naar oerelia te porten
