### ISSUE TITLE
Zoek url aanpassen

### ISSUE THREAD

**Issue by cedrikv** [OnroerendErfgoed/thesaurus-widget#23]
Uit https://github.com/OnroerendErfgoed/inventaris/issues/22#issue-239965138:

> ... Merk op dat je de parameter ctype kunt toevoegen omdat de collections enkel dienen om concepten te organiseren, maar nooit zelf toegekend worden aan iets. Waarschijnlijk is http://thesaurus.onroerenderfgoed.be/conceptschemes/ERFGOEDTYPES/c?ctype=concept&label=kerk*&mode=dijitFilteringSelect (met Acccept: application/json) echter beter omdat die alle concepten selecteert met een label dat begint met kerk (en dus bv. abdijkerk niet selecteer), wat beter werkt voor auto-aanvullen type lijsten. ...

**Comment by koenedaele** [comment]
Klopt. Collections zijn vooral nuttig in tree view en soms om als "sublijst" te dienen.
